version: '3'

tasks:
  install:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b bin v1.62.2
    silent: true
  test:
    cmds:
      - go mod tidy
      - ./bin/golangci-lint run ./...
      - go test ./...
    silent: true
  build:
    cmds:
      - go build -o bin/generator ./cmd/generator/./...
      - go build -o bin/server ./cmd/server/./...
      - go build -o bin/client ./cmd/client/./...
    silent: true
  generate:
    cmds:
      - ./bin/generator --out=./certs
    silent: true
  run:
    cmds:
      - ./bin/server --cert=./certs/pravo.tech.pem --key=./certs/pravo.tech.key --wait=5 &
      - ./bin/client --cert=./certs/pravo.tech.pem --wait=5
    silent: true