version: '3'

tasks:
  install:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b bin v1.62.2
    silent: true
  test:
    cmds:
      - go mod tidy
      - ./bin/golangci-lint run ./...
      - go test ./...
    silent: true
  build:
    cmds:
      - go build -o bin/generator ./cmd/generator/./...
      - go build -o bin/http-server ./cmd/http/server/./...
      - go build -o bin/http-client ./cmd/http/client/./...
      - go build -o bin/grpc-server ./cmd/grpc/server/./...
      - go build -o bin/grpc-client ./cmd/grpc/client/./...
    silent: true
  generate:
    cmds:
      - ./bin/generator --out=./certs
    silent: true
  http:
    cmds:
      - ./bin/http-server --cert=./certs/pravo.tech.pem --key=./certs/pravo.tech.key --wait=5 &
      - ./bin/http-client --cert=./certs/pravo.tech.pem --wait=5
    silent: true
  grpc:
    cmds:
      - ./bin/grpc-server --cert=./certs/pravo.tech.pem --key=./certs/pravo.tech.key --wait=10 &
      - ./bin/grpc-client --cert=./certs/pravo.tech.pem --wait=5
    silent: true
  api-generate:
    cmds:
      - go generate ./internal/api/./...
    silent: true