version: '3'

tasks:
  install:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b bin v1.62.2
    silent: true
  test:
    cmds:
      - go mod tidy
      - ./bin/golangci-lint run ./...
      - go test ./...
    silent: true
  build:
    cmds:
      - go build -o bin/generator ./cmd/generator/./...
    silent: true
  generate:
    cmds:
      - ./bin/generator --out=./certs